import { jsPDF } from 'jspdf';
import { SessionAnalysis } from './storage';

export const generateCaregiverReport = (sessions: SessionAnalysis[]) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let cursorY = 20;

  // Helpers
  const addText = (text: string, size = 12, bold = false, color = '#000000') => {
    doc.setFontSize(size);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setTextColor(color);
    doc.text(text, margin, cursorY);
    cursorY += size * 0.5 + 2;
  };

  const addLine = () => {
    doc.setDrawColor('#e2e8f0');
    doc.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 10;
  };

  const addWrappedText = (text: string, size = 11) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor('#475569');
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
    doc.text(lines, margin, cursorY);
    cursorY += lines.length * (size * 0.5) + 5;
  };

  // Header
  addText('CareCompanion — Weekly Health Report', 20, true, '#1e293b');
  addText(`Generated on: ${new Date().toLocaleDateString()}`, 10, false, '#64748b');
  cursorY += 10;
  addLine();

  // Summary Section
  if (sessions.length > 0) {
    const avgMood = (sessions.reduce((acc, s) => acc + s.moodScore, 0) / sessions.length).toFixed(1);
    const avgSleep = (sessions.reduce((acc, s) => acc + (s.sleepQuality || 0), 0) / sessions.filter(s => s.sleepQuality).length || 0).toFixed(1);
    const redFlagsCount = sessions.reduce((acc, s) => acc + s.redFlags.length, 0);

    addText('Executive Summary', 16, true, '#1e293b');
    addText(`Total Sessions: ${sessions.length}`, 12);
    addText(`Average Mood Score: ${avgMood} / 10`, 12);
    addText(`Average Sleep Quality: ${avgSleep} / 10`, 12);
    addText(`Active Concerns (Red Flags): ${redFlagsCount}`, 12, redFlagsCount > 0, redFlagsCount > 0 ? '#dc2626' : '#000000');
    cursorY += 10;
    addLine();
  } else {
    addText('No patient sessions recorded for this period.', 12);
    return;
  }

  // Sessions Section
  addText('Detailed Session Logs', 16, true, '#1e293b');
  cursorY += 5;

  sessions.slice().reverse().forEach((session, index) => {
    if (cursorY > 250) {
      doc.addPage();
      cursorY = 20;
    }

    const dateStr = new Date(session.timestamp).toLocaleString();
    addText(`Session ${sessions.length - index}: ${dateStr}`, 12, true, '#334155');
    addWrappedText(`Summary: ${session.summary}`);
    
    const scores = `Mood: ${session.moodScore}/10 | Sleep: ${session.sleepQuality || 'N/A'}/10 | Pain: ${session.painLevel || 'N/A'}/10`;
    addText(scores, 10, false, '#64748b');

    if (session.redFlags.length > 0) {
      addText('RED FLAGS:', 10, true, '#dc2626');
      session.redFlags.forEach(flag => {
        addText(`• ${flag}`, 10, false, '#991b1b');
      });
    }
    
    cursorY += 10;
    doc.setDrawColor('#f1f5f9');
    doc.line(margin, cursorY - 5, pageWidth - margin, cursorY - 5);
  });

  // Recommended Actions
  const totalFlags = sessions.reduce((acc, s) => acc + s.redFlags.length, 0);
  if (cursorY > 230) {
    doc.addPage();
    cursorY = 20;
  }

  cursorY += 10;
  addLine();
  addText('Recommended Actions', 16, true, '#1e293b');
  if (totalFlags > 0) {
    addWrappedText('CRITICAL: Multiple red flags or health concerns were detected across sessions. We strongly recommend reaching out to the patient or their healthcare provider for a follow-up assessment.');
    addText('1. Review specific red flag notes in session details.', 11);
    addText('2. Schedule a wellness check-in.', 11);
    addText('3. Consult with a primary physician if pain levels remain high.', 11);
  } else {
    addWrappedText('No immediate red flags detected. Continue routine check-ins to maintain baseline wellness data.');
  }

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor('#94a3b8');
    doc.text('Generated by CareCompanion AI — Confidential Health Data', margin, doc.internal.pageSize.getHeight() - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, doc.internal.pageSize.getHeight() - 10);
  }

  doc.save(`CareCompanion_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
